version: '3.5'
services: 
  graphql-api:
    build:
      context: ./graphql-api
      dockerfile: Dockerfile
    command: npm run dev
    ports:
      - 9000:80
    depends_on:
      - mongodb
      - graphql-api-watch
      - blockchain-api-2.0
    volumes:
      - ./graphql-api/dist:/app/dist:delegated
    environment:
      VIRTUAL_HOST: api.blockchain.docker
      PORT: 80
      OFFCHAIN_DB_URL: mongodb://root:password@mongodb:27017
      OFFCHAIN_DB_NAME: opschain-wallet
      OFFCHAIN_DB_USER_COLLECTION: user
      JWT_PASSWORD: 'supersecret'
      JWT_TOKEN_EXPIRE_TIME: 86400000
      BLOCKCHAIN_API: blockchain-api-2.0
    networks:
      - opschain_network

  graphql-api-watch:
    build:
      context: ./graphql-api
      dockerfile: Dockerfile
    command: npm run watch
    volumes:
      - ./graphql-api/src:/app/src:delegated
      - ./graphql-api/dist:/app/dist:delegated
    networks:
      - opschain_network

  blockchain-api-2.0:
    build:
      context: ./blockchain-api-2.0
      dockerfile: Dockerfile
    command: npm start
    ports:
      - 9005:80
    depends_on:
      - mongodb
    environment:
      VIRTUAL_HOST: api.blockchain.docker
      PORT: 80
      BLOCKCHAIN_HOST: ganache
      BLOCKCHAIN_PORT: 8545
    networks:
      - opschain_network

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017 
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: opschain-wallet
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/:delegated
      - ./db-data:/data/db
    logging:
      options:
        max-size: 100m
    networks:
      - opschain_network
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - 9003:3000
    volumes:
      - ./ui/public:/app/public:delegated
      - ./ui/src:/app/src:delegated
    depends_on:
      - graphql-api
    networks:
      - opschain_network
    environment:
      VIRTUAL_HOST: tmna.csc.docker
      REACT_APP_API_BASE_URL: http://localhost:8080
    logging:
      options:
        max-size: 10m
  test:
    build: ./test
    volumes:
      - ./test:/app:delegated
    networks:
      - opschain_network

networks:
  opschain_network:
    driver: bridge
    name: opschain_network

volumes:
  db-data: